pc_ip: valid-pc-ip
pc_username: pc-user
pc_password: pc-password

address_groups:
  - name: AD
    description: "Example AD Address Groups"
    subnets:
      - network_ip: valid-ip # Eg: 10.10.10.130
        network_prefix: valid-prefix # Eg: 32
  - name: Calm
    description: "Example Calm Address Groups"
    subnets:
      - network_ip: valid-ip # Eg: 10.10.10.130
        network_prefix: valid-prefix # Eg: 32