pc_ip: valid-pc-ip
pc_username: pc-user
pc_password: pc-password

pc_directory_services:
  directory_type: ACTIVE_DIRECTORY # only ACTIVE_DIRECTORY is supported, port 389 will be used for LDAP
  ad_name: name
  ad_domain: eng.company.com
  ad_server_ip: valid-ip
  service_account_username: username
  service_account_password: password
  role_mappings:
    - role_type: ROLE_USER_ADMIN # one of 'ROLE_CLUSTER_ADMIN', 'ROLE_USER_ADMIN', 'ROLE_CLUSTER_VIEWER', 'ROLE_BACKUP_ADMIN'
      entity_type: GROUP # one of GROUP, OU, USER
      values:
        - john_doe
        - john_smith
