pe_creds: &pe_creds
  pe_username: pe-user
  pe_password: pe-password

ad_config: &ad_config
  directory_services:
    directory_type: ACTIVE_DIRECTORY # only ACTIVE_DIRECTORY is supported, port 389 will be used for LDAP
    ad_name: name
    ad_domain: eng.company.com
    ad_server_ip: valid-ip
    service_account_username: username
    service_account_password: password
    role_mappings:
      - role_type: ROLE_USER_ADMIN # one of 'ROLE_CLUSTER_ADMIN', 'ROLE_USER_ADMIN', 'ROLE_CLUSTER_VIEWER', 'ROLE_BACKUP_ADMIN'
        entity_type: GROUP # one of GROUP, OU, USER
        values:
          - john_doe
          - john_smith

clusters:
  # configure the below clusters in the site
  valid-cluster-01-ip:
    # Use global pe creds for authentication
    <<: *pe_creds
    # Use global ad config
    <<: *ad_config
  valid-cluster-02-ip:
    # can define locally as well
    pe_username: pe-user
    pe_password: pe-password
    # can define locally as well
    directory_services:
      directory_type: ACTIVE_DIRECTORY # only ACTIVE_DIRECTORY is supported, port 389 will be used for LDAP
      ad_name: name1
      ad_domain: eng.company-1.com
      ad_server_ip: valid-ip-1
      service_account_username: username
      service_account_password: password
      role_mappings:
        - role_type: ROLE_USER_ADMIN # one of 'ROLE_CLUSTER_ADMIN', 'ROLE_USER_ADMIN', 'ROLE_CLUSTER_VIEWER', 'ROLE_BACKUP_ADMIN'
          entity_type: GROUP # one of GROUP, OU, USER
          values:
            - john_doe
            - john_smith
