---
ncm_vm_ip: valid-ip
ncm_username: valid-user
ncm_password: valid-pass

DEFAULT_ACCOUNT_NAME: &DEFAULT_ACCOUNT_NAME
  ACCOUNT_NAME: NTNX_LOCAL_AZ

# List of DSL BPs
bp_list:
  - dsl_file: calm-dsl-bps/blueprints/LAMP/LAMP.py
    name: LAMP-dsl
    app_name: LAMP-dsl
    runtime_vars: ""

# Projects to deploy above BPs to
projects:
  - PROJECT_NAME: project-cluster-1
    CLUSTER_NAME: cluster1
    SUBNET_NAME: cluster1-subnet1
    <<: *DEFAULT_ACCOUNT_NAME
  - PROJECT_NAME: project-cluster-2
    CLUSTER_NAME: cluster2
    SUBNET_NAME: cluster2-subnet2
    <<: *DEFAULT_ACCOUNT_NAME