pc_ip: valid-pc-ip
pc_username: pc-user
pc_password: pc-password

objects:
  directory_services:
    - ad_name: name
      ad_domain: eng.company.com
      ad_server_ip: valid-ip
      service_account_username: username
      service_account_password: password
      ad_users:
        - darshan@eng.company.com
        - kousalya@eng.company.com