pc_ip: valid-pc-ip
pc_username: pc-user
pc_password: pc-password

pc_name_servers_list:
  - valid-ip-1
  - valid-ip-2
pc_ntp_servers_list:
  - 0.us.pool.ntp.org
  - 1.us.pool.ntp.org
  - 2.us.pool.ntp.org