pc_ip: valid-pc-ip
pc_username: pc-user
pc_password: pc-password
admin_pc_password: admin-pc-password

eula:
  username: Nutanix
  company_name: Nutanix
  job_title: Backend Engineer

enable_pulse: true