pc_ip: valid-pc-ip
pc_username: pc-user
pc_password: pc-password

objects:
  objectstores:
    - name: objectstore01
      domain: eng.company.com
      cluster: cluster01
      network: subnet01
      # Specify 4 static IPs
      static_ip_list:
        - ip1
        - ip2
        - ip3
        - ip4
      num_worker_nodes: 1
      buckets:
        - name: bucket1
          user_access_list:
            - darshan@eng.company.com
            - kousalya@eng.company.com
        - name: bucket2
          user_access_list:
            - darshan@eng.company.com
            - kousalya@eng.company.com
    - name: objectstore02
      domain: eng.company.com
      cluster: cluster01
      network: subnet01
      # Specify 4 static IPs
      static_ip_list:
        - ip1
        - ip2
        - ip3
        - ip4
      num_worker_nodes: 1
      buckets:
        - name: bucket1
          user_access_list:
            - darshan@eng.company.com
            - kousalya@eng.company.com