---
# This configuration is used to facilitate Initial PC configurations includind enabling FC

# Global variables, which can be inherited in blocks
pc_creds: &pc_creds
  # This can be admin/ ad user. Note ad creds will be used after adding AD to PC
  pc_username: pc-user
  pc_password: pc-password
  # New admin password for PC
  admin_pc_password: admin-pc-password

pe_creds: &pe_creds
  # This can be admin/ ad user. Note ad creds will be used after adding AD to PE
  pe_username: pe-user
  pe_password: pe-password

pc_eula: &eula
  eula:
    username: Nutanix
    company_name: Nutanix
    job_title: Backend Engineer

pulse: &pulse
  enable_pulse: true

fc: &fc
  # FC configuration to enable & generate FC API Key
  enable_fc: true
  generate_fc_api_key: true
  fc_alias_key_name: api_key1 # name of the API key generated in FC

pod:
  pod_name: pod_1
  # Pod Blocks where initial PC configuration needs to be executed
  pod_blocks:
    - pod_block_name: block-1
      # PC IP where initial PC configuration needs to be executed
      pc_ip: x.x.x.x
      # Use global pc creds
      <<: *pc_creds
      # Use global eula config
      <<: *eula
      # Use global pulse config
      <<: *pulse
      # Use global FC confg
      <<: *fc
      # Clusters/PE to Register to PC
      clusters:
        valid-cluster-ip:
          # Use global pe creds
          <<: *pe_creds
      
    - pod_block_name: block-2
      # PC IP where initial PC configuration needs to be executed
      pc_ip: x.x.x.x
      # Use global pc creds
      <<: *pc_creds
      # Use global eula config
      <<: *eula
      # Use global pulse config
      <<: *pulse
      # Clusters/PE to Register to PC
      clusters:
        valid-cluster-ip:
          # Use global pe creds
          <<: *pe_creds
