pc_ip: valid-pc-ip
pc_username: pc-user
pc_password: pc-password

recovery_plans:
  - name: AZ01-RP-Calm
    desc: "Example Recovery plan for AppType CalmAppliance"
    primary_location:
      # Primary location is set to Local block/ AZ
      availability_zone: valid-local-block-pc-ip
      # cluster: bucky01-dev # Optional. Required only for Local AZ to Local AZ
    recovery_location:
      availability_zone: valid-remote-pc-ip
      # cluster: bucky02-dev # Optional. Required only for Local AZ to Local AZ
    stages:
      #- vms:
      #- name: ubuntu-01
      #enable_script_exec: true
      #delay: 2
      - categories:
          - key: AppType
            value: CalmAppliance
    network_type: NON_STRETCH # NON_STRETCH/STRETCH
    network_mappings:
      - primary:
          test:
            name: valid-subnet-name
            #gateway_ip: gateway_ip Optional
            #prefix: network_prefix
          prod:
            name: valid-subnet-name
            #gateway_ip: gateway_ip
            #prefix: network_prefix
        recovery:
          test:
            name: valid-subnet-name
            #gateway_ip: gateway_ip
            #prefix: network_prefix
          prod:
            name: valid-subnet-name
            #gateway_ip: gateway_ip
            #prefix: network_prefix