pc_ip: valid-pc-ip
pc_username: pc-user
pc_password: pc-password

security_policies:
  - name: Example-AZ01-Calm
    description: Example Security Policy
    allow_ipv6_traffic: true # true/ false # Policy rules apply only to IPv4 Traffic and all IPv6 traffic are blocked by default.
    hitlog: true # true/ false # Log traffic flow hits on the policy rules
    # Only app rules are supported for now
    app_rule:
      policy_mode: MONITOR # APPLY/MONITOR
      # Secure this app
      target_group:
        categories:
          AppType: AZ01LAMP01
      inbounds:
        - categories:
            AppTier:
              - WEB
          address:
            name: Calm
          protocol:
            service:
              name: ssh
        - categories:
            AppTier:
              - APP
          udp:
            - start_port: 82
              end_port: 8080
          address:
            name: Calm
          protocol:
            service:
              name: ssh
        - categories:
            AppTier:
              - DB
          address:
            name: Calm
          protocol:
            service:
              name: ssh
      outbounds:
        - address:
            name: NVD_AD
          protocol:
            service:
              name: dns