pc_ip: valid-pc-ip
pc_username: pc-user
pc_password: pc-password

service_groups:
  - name: ngt
    description: Example Service Group NGT - TCP
    service_details:
      tcp:
        - "2074"
  - name: dns
    description: Example Service Group DNS - UDP
    service_details:
      udp:
        - "53"