pc_ip: valid-pc-ip
pc_username: pc-user
pc_password: pc-password

images:
  # Images that needs to be uploaded to the PC clusters
  - url: http://url-to-download-image-from # url where the image file is located
    name: image-name # name of the image to be uploaded to the PC clusters
    image_type: DISK_IMAGE # image type that is uploaded. Allowed values: DISK_IMAGE, ISO_IMAGE
    cluster_name_list: [cluster-1, cluster-2] # cluster names to upload images. We can upload to multiple clusters
