# Global variables, which can be inherited in blocks
pc_creds: &pc_creds
  pc_username: pc-user
  pc_password: pc-password

# A single pod can support up to 2,000 edge clusters
pod:
  pod_name: "pod_east"
  # Each block can support a maximum of 400 edge locations
  pod_blocks:
    - pod_block_name: block-01
      pc_ip: valid-block-pc-ip
      # Using globally declared pc credentials
      <<: *pc_creds
      # Deploy edge-clusters managed by this block
      edge-sites:
        - site_name: site-01
          # List of node block serials, available nodes in the provided block serials will be used for cluster deployment
          # node_block_serials is optional, if node-serials are provided in each cluster configuration for this site
          node_block_serials: ["node-block-serial-1", "node-block-serial-2"]
          # To re-use the existing network setting set use_existing_network_settings to ture
          use_existing_network_settings: true
          # HOST, CVM and IPMI network configuration. This configuration is not required, if network settings are re-used 
          network:
            # Provide start and end ip address for MGMT static IPs
            # mgmt_static_ips = [start_ip, end_ip]
            mgmt_static_ips: []
            # Provide Gateway and Netmask for management network
            mgmt_gateway: ""
            mgmt_netmask: ""
            # Provide start and end ip address for IPMI static IPs
            # ipmi_static_ips = [start_ip, end_ip]
            ipmi_static_ips: []
            # Provide Gateway and Netmask for IPMI network
            ipmi_gateway: ""
            ipmi_netmask: ""
          # set re-image to true for re-imaging with provided aos, ahv versions
          re-image: true
          # the below section can be empty if re-image is not required
          imaging_parameters:
            aos_version: "6.5.1.8"
            hypervisor_type: "kvm"
            hypervisor_version: "20201105.30411"
          # Cluster details for deployment & imaging
          clusters:
            - cluster_name: site01-cluster-01
              # Cluster size will be the number of nodes for deployment
              cluster_size: 3
              cluster_vip: valid-cluster-vip-ip
              # cvm_ram is Gigabytes. Minimum 12, no maximum. Default set it to 12.
              cvm_ram: 12
              # Provided node serials will be used for this cluster deployment.
              # Node serials need not be a part of blocks_serial_numbers mentioned above
              # node_serials is not mandatory. If node_serials are not provided, available nodes in the provided node_block_serials will be used.
              node_serials: ["node-serial-1", "node-serial-2", "node-serial-3"]
              # Nutanix supports RF2, and also RF3 only if the cluster has 5+ nodes
              redundancy_factor: 2
            - cluster_name: site01-cluster-02
              cluster_size: 1
              cluster_vip: valid-cluster-vip-ip
              cvm_ram: 12
              # Re-image can be set to true or false for a particular cluster deployment
              re-image: false
              redundancy_factor: 2
              # HOST, CVM and IPMI network configuration for this cluster deployment. This will not used the site level network configuration.
              network:
                # Provide start and end ip address for MGMT static IPs
                # mgmt_static_ips = [start_ip, end_ip]
                mgmt_static_ips: ["valid-start-ip", "valid-end-ip"]
                # Provide Gateway and Netmask for management network
                mgmt_gateway: "valid-gateway"
                mgmt_netmask: "valid-netmask"
                # Provide start and end ip address for IPMI static IPs
                # ipmi_static_ips = [start_ip, end_ip]
                ipmi_static_ips: []
                # Provide Gateway and Netmask for IPMI network
                ipmi_gateway: ""
                ipmi_netmask: ""
        - site_name: site-02
          # List of node block serials, available nodes in the provided block serials will be used for cluster deployment
          # node_block_serials is optional, if node-serials are provided in each cluster configuration for this site
          node_block_serials: ["node-block-serial-1", "node-block-serial-2"]
          # To re-use the existing network setting set use_existing_network_settings to ture
          use_existing_network_settings: true
          # HOST, CVM and IPMI network configuration. This configuration is not required, if network settings are re-used 
          network:
            # Provide start and end ip address for MGMT static IPs
            # mgmt_static_ips = [start_ip, end_ip]
            mgmt_static_ips: []
            # Provide Gateway and Netmask for management network
            mgmt_gateway: ""
            mgmt_netmask: ""
            # Provide start and end ip address for IPMI static IPs
            # ipmi_static_ips = [start_ip, end_ip]
            ipmi_static_ips: []
            # Provide Gateway and Netmask for IPMI network
            ipmi_gateway: ""
            ipmi_netmask: ""
          # set re-image to true for re-imaging with provided aos, ahv versions
          re-image: true
          # the below section can be empty if re-image is not required
          imaging_parameters:
            aos_version: "6.5.1.8"
            hypervisor_type: "kvm"
            hypervisor_version: "20201105.30411"
          # Cluster details for deployment & imaging
          clusters:
            - cluster_name: site02-cluster-01
              # Cluster size will be the number of nodes for deployment
              cluster_size: 3
              cluster_vip: valid-cluster-vip-ip
              # cvm_ram is Gigabytes. Minimum 12, no maximum. Default set it to 12.
              cvm_ram: 12
              # Provided node serials will be used for this cluster deployment.
              # Node serials need not be a part of blocks_serial_numbers mentioned above
              # node_serials is not mandatory. If node_serials are not provided, available nodes in the provided node_block_serials will be used.
              node_serials: ["node-serial-1", "node-serial-2", "node-serial-3"]
              # Nutanix supports RF2, and also RF3 only if the cluster has 5+ nodes
              redundancy_factor: 2
            - cluster_name: site02-cluster-02
              cluster_size: 1
              cluster_vip: valid-cluster-vip-ip
              cvm_ram: 12
              # Re-image can be set to true or false for a particular cluster deployment
              re-image: false
              redundancy_factor: 2
              # HOST, CVM and IPMI network configuration for this cluster deployment. This will not used the site level network configuration.
              network:
                # Provide start and end ip address for MGMT static IPs
                # mgmt_static_ips = [start_ip, end_ip]
                mgmt_static_ips: []
                # Provide Gateway and Netmask for management network
                mgmt_gateway: ""
                mgmt_netmask: ""
                # Provide start and end ip address for IPMI static IPs
                # ipmi_static_ips = [start_ip, end_ip]
                ipmi_static_ips: []
                # Provide Gateway and Netmask for IPMI network
                ipmi_gateway: ""
                ipmi_netmask: ""
