---
# Global variables, which can be inherited in clusters
pc_creds: &pc_creds
  pc_username: pc-user
  pc_password: pc-password

pe_creds: &pe_creds
  pe_username: pe-user
  pe_password: pe-password

ad_config: &ad_config
  directory_services:
    directory_type: ACTIVE_DIRECTORY # only ACTIVE_DIRECTORY is supported, port 389 will be used for LDAP
    ad_name: name
    ad_domain: eng.company.com
    ad_server_ip: valid-ip
    service_account_username: username
    service_account_password: password
    role_mappings:
      - role_type: ROLE_USER_ADMIN # one of 'ROLE_CLUSTER_ADMIN', 'ROLE_USER_ADMIN', 'ROLE_CLUSTER_VIEWER', 'ROLE_BACKUP_ADMIN'
        entity_type: GROUP # one of GROUP, OU, USER
        values:
          - john_doe
          - john_smith

cluster_eula: &eula
  eula:
    username: Nutanix
    company_name: Nutanix
    job_title: Backend Engineer

pulse: &pulse
  enable_pulse: true

pe_container: &pe_container
  name: Automation-container
  # All these below parameters are optional
  #storage_pool_uuid: uuid # Which storage pool to use, comment it to auto pick storage pool
  reserved_in_gb: 1 # Represents the minimum exclusively reserved storage capacity available for the storage container
  advertisedCapacity_in_gb: 1 # Represents the maximum storage capacity available for the storage container to use
  replication_factor: 2 # Number of data copies to maintain
  compression_enabled: true # Only Inline compression is supported yet
  compression_delay_in_secs: 0
  erasure_code: "OFF" # OFF/ ON # Erasure code requires a minimum of 4 nodes when using RF2 and a minimum of 6 nodes when using RF3
  on_disk_dedup: "OFF" # OFF/ ON # Deduplication is not supported with fewer than 3 nodes
  nfsWhitelistAddress: [ ] # Access list for storage container

pe_networks: &pe_networks
  name: "vlan-110"
  subnet_type: VLAN # only VLAN is supported yet
  vlan_id: 110
  network_ip: valid-ip
  network_prefix: 24
  default_gateway_ip: valid-ip
  # comment pool_list section if there are no pools for the subnet
  pool_list:
    - range: "valid-ip-start valid-ip-end" # Eg "10.10.10.31 10.10.10.40"
  #  comment dhcp_options section if you don't want dhcp. Over-riding dhcp is not supported yet
  dhcp_options:
    domain_name_server_list: [ 10.10.10.10 ]
    domain_search_list: [ eng.company.com ]
    domain_name: eng.company.com

pods:
  - AZ01:
      pc_ip: valid-local-pc-ip
      # Using globally declared pc credentials
      <<: *pc_creds
      remote_azs:
        # remote AZ details, only Physical location is supported yet
        valid-remote-pc-ip:
          username: remote-pc-user
          password: remote-pc-password
      # To create categories in current PC
      categories:
        # Scenario 1, add values to an existing category
        - name: AppType # name of existing category
          description: "AppType CalmAppliance"
          values: [ "CalmAppliance" ]
        # Scenario 2, create a new category with values
        - name: AZ01-DR-01
          description: "AZ01-DR-01 RPO1h"
          values: [ "RPO1h" ]
      # To create policies in current PC
      protection_rules:
        - name: AZ01-AZ02-Calm
          desc: "Example Protection Rule for CalmAppliance"
          protected_categories:
            AppType:
              - CalmAppliance
          schedules:
            - source:
                # Source should always be Local AZ i.e local PC
                availability_zone: valid-local-pc-ip
                cluster: source-cluster
              destination:
                # Source should always be one of the remote AZs
                availability_zone: valid-remote-pc-ip
                cluster: destination-cluster
              protection_type: ASYNC # ASYNC/ SYNC
              # if protection_type is SYNC
              #auto_suspend_timeout: 10
              # if protection_type is ASYNC
              rpo: 1
              rpo_unit: HOUR # MINUTE/HOUR/DAY/WEEK
              snapshot_type: "CRASH_CONSISTENT" # APPLICATION_CONSISTENT/CRASH_CONSISTENT
              local_retention_policy:
                # For Linear Retention type (Retains the n most recent snapshots. A value of 12 means that the 12 most recent snapshots are retained)
                num_snapshots: 1
                  # For Roll-up retention type (Maintains a rolling window of snapshots for every schedule, starting with the hourly schedule and ending with the schedule created for the specified retention period)
                  #rollup_retention_policy:
                  #snapshot_interval_type: YEARLY # DAILY/WEEKLY/MONTHLY/YEARLY
                #multiple: 2
              remote_retention_policy:
                # For Linear Retention type
                num_snapshots: 1
                  # For Roll-up retention type
                  #rollup_retention_policy:
                  #snapshot_interval_type: YEARLY # HOURLY/DAILY/WEEKLY/MONTHLY/YEARLY
                #multiple: 2
      recovery_plans:
        - name: AZ01-RP-Calm
          desc: "Example Recovery plan for AppType CalmAppliance"
          primary_location:
            # Primary location is set to Local AZ
            availability_zone: valid-local-pc-ip
            # cluster: bucky01-dev # Optional. Required only for Local AZ to Local AZ
          recovery_location:
            availability_zone: valid-remote-pc-ip
            # cluster: bucky02-dev # Optional. Required only for Local AZ to Local AZ
          stages:
            #- vms:
              #- name: ubuntu-01
                #enable_script_exec: true
                #delay: 2
            - categories:
                - key: AppType
                  value: CalmAppliance
          network_type: NON_STRETCH # NON_STRETCH/STRETCH
          network_mappings:
            - primary:
                test:
                  name: valid-subnet-name
                  #gateway_ip: gateway_ip Optional
                  #prefix: network_prefix
                prod:
                  name: valid-subnet-name
                  #gateway_ip: gateway_ip
                  #prefix: network_prefix
              recovery:
                test:
                  name: vlan110
                  #gateway_ip: gateway_ip
                  #prefix: network_prefix
                prod:
                  name: vlan110
                  #gateway_ip: gateway_ip
                  #prefix: network_prefix
      address_groups:
        - name: AD
          description: "Example AD Address Groups"
          subnets:
            - network_ip: valid-ip # Eg: 10.10.10.130
              network_prefix: valid-prefix # Eg: 32
        - name: Calm
          description: "Example Calm Address Groups"
          subnets:
            - network_ip: valid-ip # Eg: 10.10.10.130
              network_prefix: valid-prefix # Eg: 32
      service_groups:
        - name: ngt
          description: Example Service Group NGT - TCP
          service_details:
            tcp:
              - "2074"
        - name: dns
          description: Example Service Group DNS - UDP
          service_details:
            udp:
              - "53"
      security_policies:
        - name: Example-AZ01-Calm
          description: Example Security Policy
          allow_ipv6_traffic: true # true/ false # Policy rules apply only to IPv4 Traffic and all IPv6 traffic are blocked by default.
          hitlog: true # true/ false # Log traffic flow hits on the policy rules
          # Only app rules are supported for now
          app_rule:
            policy_mode: MONITOR # APPLY/MONITOR
            # Secure this app
            target_group:
              categories:
                AppType: AZ01LAMP01
            inbounds:
              - categories:
                  AppTier:
                    - WEB
                address:
                  name: Calm
                protocol:
                  service:
                    name: ssh
              - categories:
                  AppTier:
                    - APP
                udp:
                  - start_port: 82
                    end_port: 8080
                address:
                  name: Calm
                protocol:
                  service:
                    name: ssh
              - categories:
                  AppTier:
                    - DB
                address:
                  name: Calm
                protocol:
                  service:
                    name: ssh
            outbounds:
              - address:
                  name: NVD_AD
                protocol:
                  service:
                    name: dns
      clusters:
        # specify the names of clusters if they are already registered to a PC defined above in the AZ
        # else specify the ip if they need to be registered to the PC
        valid-pe-ip-or-name:
          name: cluster-01 # Optional if name is already provided above
          # Use global pe creds
          <<: *pe_creds
          # Use global eula config
          <<: *eula
          # Use global pulse config
          <<: *pulse
          # Use global ad config
          <<: *ad_config
          dsip: valid-ip
          networks:
            # Use global network config
            - <<: *pe_networks
          containers:
            # Use global storage container config
            - <<: *pe_container
        valid-pe-ip-or-name:
          name: cluster-02 # Optional if name is already provided above
          # Use global pe creds
          <<: *pe_creds
          # Over-ride global eula config
          eula:
            username: username
            company_name: Nutanix
            job_title: title
          # Use global pulse config
          <<: *pulse
          # Over-ride global ad config
          ad_config:
            directory_services:
              directory_type: ACTIVE_DIRECTORY # only ACTIVE_DIRECTORY is supported, port 389 will be used for LDAP
              ad_name: some-other-name
              ad_domain: eng.company.com
              ad_server_ip: valid-ip
              service_account_username: username
              service_account_password: password
              role_mappings:
                - role_type: ROLE_USER_ADMIN # one of 'ROLE_CLUSTER_ADMIN', 'ROLE_USER_ADMIN', 'ROLE_CLUSTER_VIEWER', 'ROLE_BACKUP_ADMIN'
                  entity_type: GROUP # one of GROUP, OU, USER
                  values:
                    - yash
                    - naveen
          dsip: valid-ip
          networks:
            # Use global network config and add another network
            - <<: *pe_networks
            - name: "vlan-200"
              subnet_type: VLAN # only VLAN is supported yet
              vlan_id: 200
              network_ip: valid-ip
              network_prefix: 24
              default_gateway_ip: valid-ip
              # comment pool_list section if there are no pools for the subnet
              pool_list:
                - range: "valid-ip-start valid-ip-end" # Eg "10.10.10.31 10.10.10.40"
              #  comment dhcp_options section if you don't want dhcp. Over-riding dhcp is not supported yet
              dhcp_options:
                domain_name_server_list: [ 10.10.10.10 ]
                domain_search_list: [ eng.company.com ]
                domain_name: eng.company.com
          containers:
            # Use global storage container config and add another container
            - <<: *pe_container
            - name: Automation-container-2
              # All these below parameters are optional
              #storage_pool_uuid: uuid # Which storage pool to use, comment it to auto pick storage pool
              reserved_in_gb: 1 # Represents the minimum exclusively reserved storage capacity available for the storage container
              advertisedCapacity_in_gb: 1 # Represents the maximum storage capacity available for the storage container to use
              replication_factor: 2 # Number of data copies to maintain
              compression_enabled: true # Only Inline compression is supported yet
              compression_delay_in_secs: 0
              erasure_code: "OFF" # OFF/ ON # Erasure code requires a minimum of 4 nodes when using RF2 and a minimum of 6 nodes when using RF3
              on_disk_dedup: "OFF" # OFF/ ON # Deduplication is not supported with fewer than 3 nodes
              nfsWhitelistAddress: [ ] # Access list for storage container