name: Trigger Black duck Workflow
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name to checkout'
        required: true

jobs:
  create-python-environment:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        #  gives you either a new virtualenv, or restores an old one based on
        #  the requirements*.txt -file.
    - uses: syphar/restore-virtualenv@v1
      id: cache-virtualenv
      with:
        requirement_files: "**/requirements/*.in"
    - uses: syphar/restore-pip-download-cache@v1
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      with:
        requirement_files: "**/requirements/*.in"
      # the package installation will only be executed when the
      # requirements*.txt - file has changed.
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools
        pip-compile --output-file=requirements/dev.txt requirements/dev.in 
        pip install -r requirements/dev.txt
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'
  run-python-workflow:
    needs: create-python-environment
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Restore cache
        uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
        with:
          requirement_files: "**/requirements/*.in"
      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run Blackduck Detect
        uses: synopsys-sig/detect-action@v0.3.4
        env:
          DETECT_PROJECT_NAME: ztf-int
          DETECT_PROJECT_VERSION_NAME: 1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          detect-version: 9.1.0
          blackduck-url: ${{ secrets.BLACKDUCK_URL }}
          blackduck-api-token: ${{ secrets.BLACKDUCK_SCAN_ACTION_ACCESS_TOKEN }}
          detect-trust-cert: TRUE
          scan-mode: INTELLIGENT
          fail-on-all-policy-severities: FALSE
