name: Trigger Github Actions

on:
  pull_request_review:
    types: [submitted]    

env:
  GH_TOKEN: ${{ github.token }}
  BRANCH_NAME: ${{ github.event.pull_request.head.ref }} 

jobs:
  call-python-workflow:
    if: ${{ github.event.review.state == 'approved' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: tj-actions/changed-files@v35
        id: changed_files
        with:
          json: "true"
      - name: Print changed files
        run: |
          echo "Changed files: ${{ steps.changed_files.outputs.all_changed_files }}"
      - name: Call imaging if new-site config file changed
        if: contains(steps.changed_files.outputs.all_changed_files, 'config/new-site.json')
        run: |
          gh workflow run trigger-python-workflows.yml -f file=config/new-site.json -f workflow=imaging -f branch=${{ env.BRANCH_NAME }}
      - name: Call cluster-config if pod-config file changed
        if: contains(steps.changed_files.outputs.all_changed_files, 'config/pod-config.yml')
        run: |
          gh workflow run trigger-python-workflows.yml -f file=config/pod-config.yml -f workflow=pod-config -f branch=${{ env.BRANCH_NAME }}
      - name: Call vm-workloads if create_vm_workloads file changed
        if: contains(steps.changed_files.outputs.all_changed_files, 'config/create-vm-workloads.json')
        run: |
          gh workflow run trigger-python-workflows.yml -f file=config/create_vm_workloads.json -f workflow=create-vm-workloads -f branch=${{ env.BRANCH_NAME }}
      - name: Call edge-ai-workloads if edge_ai file changed
        if: contains(steps.changed_files.outputs.all_changed_files, 'config/edge-ai.json')
        run: |
          gh workflow run trigger-python-workflows.yml -f file=config/edge-ai.json -f workflow=calm-edgeai-vm-workload -f branch=${{ env.BRANCH_NAME }}
